description:
  - "Here are some projects I've built while learning and exploring different technologies."

projects:
  - name: "Campus Event Manager"
    description: "Full-stack web app for managing university events and RSVPs"
    additional_description: "Built with React and Node.js, this platform allows students to discover campus events, RSVP, and receive notifications. Features include user authentication, event filtering by category, and an admin dashboard for event organizers."
    date: "Jan 2024"
    svgIcons:
      - gatsby
      - reactjs
      - tailwind
      - aws
    actions:
      - text: GitHub
        link: https://github.com/[your-username]/[project-name]
      - text: Live Demo
        link: https://[your-demo-url].com
        color: purple

  - name: "Study Buddy"
    description: "ML-powered app that generates flashcards from lecture notes"
    additional_description: "Developed a Python application using natural language processing to automatically extract key concepts from PDF lecture notes and generate study flashcards. Implemented with spaCy for NLP, Flask for the backend, and a simple React frontend."
    date: "Sep 2023"
    svgIcons:
      - gatsby
      - reactjs
      - tailwind
      - aws
    actions:
      - text: GitHub
        link: https://github.com/[your-username]/[project-name]
      - text: Demo Video
        video: demo.mp4
        color: purple

  - name: "Algorithm Visualizer"
    description: "Interactive web tool for visualizing sorting and graph algorithms"
    additional_description: "Created an educational platform to help students understand how algorithms work through step-by-step visualizations. Includes sorting algorithms (QuickSort, MergeSort, BubbleSort) and graph algorithms (BFS, DFS, Dijkstra's)."
    date: "May 2023"
    svgIcons:
      - gatsby
      - reactjs
      - tailwind
      - aws
    actions:
      - text: GitHub
        link: https://github.com/[your-username]/[project-name]
      - text: Try It
        link: https://[your-demo-url].com
        color: purple
  - name: "Discord Study Bot"
    description: "Bot that helps study groups track pomodoro sessions"
    date: "Nov 2023"
    actions:
      - text: GitHub
        link: https://github.com/[your-username]/[project-name]

  - name: "Personal Budget Tracker"
    description: "CLI tool for tracking expenses with data visualization"
    date: "Aug 2023"
    actions:
      - text: GitHub
        link: https://github.com/[your-username]/[project-name]
